### ISSUE TITLE
chat_id'yi nasıl alıyorsunuz?

### ISSUE THREAD

**Issue by onurozgurozkan** [Projekod/Bulutfon-Telegram-Bildirim-Botu#1]
Telegram'da botlar karşı taraf yazı yazmadan cevap veremiyor. Bu durumda chat_id'yi nasıl alıyorsunuz. Yani bildirim ilk önce Bot tarafından nasıl başlatılıyor?

**Comment by aligundogdu** [comment]
Botlar eklendikleri chat istekleri ve mesaj isteklerinin datasını bize telegram getUpdates apisi ile sunuyor bizde içerisinden lazım olanı seçip kullanıyoruz. https://core.telegram.org/bots/api#getupdates

gelen update bilgilerinin içerisinde chat id kullanıcı id gibi detaylar var botu buna göre şekillendirmek mümkün.

**Comment by onurozgurozkan** [comment]
@aligundogdu bilgilendirme için çok teşekkur ederim.
